# Generated by Django 6.1 on 2026-09-01 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='슬러그')),
                ('cover_image', models.ImageField(blank=True, upload_to='journal/%Y/%m/', verbose_name='대표 이미지')),
                ('content', models.TextField(verbose_name='본문')),
                ('is_published', models.BooleanField(default=True, verbose_name='공개 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
            ],
            options={
                'verbose_name': '저널 게시글',
                'verbose_name_plural': '저널 게시글',
                'ordering': ['-created_at'],
            },
        ),
    ]
