# Generated by Django 5.2.17 on 2026-09-28 06:34

from django.db import migrations, models


def create_about_page(apps, schema_editor):
    # 기존 About 페이지에 있던 안내 문구로 시작 (관리자에서 수정)
    AboutPage = apps.get_model('pages', 'AboutPage')
    if not AboutPage.objects.exists():
        AboutPage.objects.create(
            title='ABOUT',
            content='여기에 브랜드 소개 문구를 작성하세요. 언제, 누가, 어떤 계기로 시작했는지,\n'
                    '어떤 기준으로 빈티지 아이템을 큐레이션 하는지 등을 적으면 좋습니다.',
        )


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_journalpost_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ABOUT', max_length=100, verbose_name='제목')),
                ('image', models.ImageField(blank=True, upload_to='about/', verbose_name='대표 이미지')),
                ('content', models.TextField(help_text='줄바꿈은 그대로 화면에 표시됩니다.', verbose_name='본문')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': 'About 페이지',
                'verbose_name_plural': 'About 페이지',
            },
        ),
        migrations.RunPython(create_about_page, migrations.RunPython.noop),
    ]
