# Generated by Django 5.2.17 on 2026-09-28 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_about_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal/%Y/%m/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='pages.journalpost')),
            ],
            options={
                'verbose_name': '저널 이미지',
                'verbose_name_plural': '저널 이미지',
                'ordering': ['order', 'id'],
            },
        ),
    ]
