# Generated by Django 5.2.17 on 2026-09-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_journal_content_and_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeIntro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, help_text='홈 화면 상품 사진 위에 표시돼요. 줄바꿈은 그대로 보이고, 비워두면 소개글 영역이 나타나지 않아요.', verbose_name='소개글')),
                ('is_visible', models.BooleanField(default=True, verbose_name='표시')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
            options={
                'verbose_name': '홈 소개글',
                'verbose_name_plural': '홈 소개글',
            },
        ),
    ]
