"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# 배포 환경에서는 환경변수로 값을 주입하고, 로컬에서는 아래 기본값을 사용합니다.
SECRET_KEY = os.environ.get(
    'SECRET_KEY',
    'django-insecure-&cdbx#!g^jqfft95f7#7-)ju9x4l#g0ge-4rtucp*gm$ic9eb1',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'healthcheck.railway.app']  # 마지막은 Railway 헬스체크용
CSRF_TRUSTED_ORIGINS = []

# Railway가 자동으로 넣어주는 공개 도메인 + 직접 연결한 도메인(쉼표 구분)
_hosts = [os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')] + os.environ.get('ALLOWED_HOSTS', '').split(',')
for _host in filter(None, (h.strip() for h in _hosts)):
    ALLOWED_HOSTS.append(_host)
    CSRF_TRUSTED_ORIGINS.append(f'https://{_host}')

if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # 우리 프로젝트 앱들
    'products',
    'cart',
    'orders',
    'accounts',
    'pages',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # 배포 환경 정적 파일(CSS 등) 서빙
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'cart.context_processors.cart',  # 모든 템플릿에서 장바구니 개수 사용
                'products.context_processors.nav_categories',  # 상품 목록 위 카테고리 바
                'pages.context_processors.social_links',  # 메인 메뉴 instagram / mail 주소
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

# DATABASE_URL 환경변수가 있으면(배포: PostgreSQL) 그걸 쓰고, 없으면 로컬 SQLite 사용
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600,
    )
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'  # collectstatic 결과가 모이는 곳

STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage'},
}
# collectstatic을 돌리지 않아도 WhiteNoise가 static/ 폴더와 앱(admin 등)의 정적 파일을 직접 서빙
WHITENOISE_USE_FINDERS = True


def _long_cache_for_fonts(headers, path, url):
    # 폰트 파일명에 버전(.v133)이 들어 있어 내용이 바뀌면 이름도 바뀜 → 1년 동안 캐시
    if url.startswith('/static/fonts/'):
        headers['Cache-Control'] = 'public, max-age=31536000, immutable'


WHITENOISE_ADD_HEADERS_FUNCTION = _long_cache_for_fonts

# 상품 사진 등 사용자가 업로드하는 파일 (Media files)
# 배포 시에는 MEDIA_ROOT를 영구 볼륨 경로(예: /data/media)로 지정해야 재배포해도 사진이 남아요.
MEDIA_URL = 'media/'
MEDIA_ROOT = Path(os.environ.get('MEDIA_ROOT', BASE_DIR / 'media'))

LOGIN_URL = 'accounts:login'
LOGIN_REDIRECT_URL = 'products:list'
LOGOUT_REDIRECT_URL = 'products:list'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}


# 토스페이먼츠 결제 키
# 기본값은 토스페이먼츠 공식 문서의 공개 테스트 키입니다(실제 돈이 나가지 않음).
# 개발자센터(https://developers.tosspayments.com)에서 발급받은 내 키로 환경변수를 설정하세요.
TOSS_CLIENT_KEY = os.environ.get('TOSS_CLIENT_KEY', 'test_gck_docs_Ovk5rk1EwkEbP0W43n07xlzm')
TOSS_SECRET_KEY = os.environ.get('TOSS_SECRET_KEY', 'test_gsk_docs_OaPz8L5KdmQXkzRz3y47BMw6')

# 메인 메뉴의 instagram / mail 링크. 비어 있으면 메뉴는 보이지만 눌러도 아무 동작도 하지 않음.
# 예) INSTAGRAM_URL=https://www.instagram.com/계정명/  CONTACT_EMAIL=hello@example.com
INSTAGRAM_URL = os.environ.get('INSTAGRAM_URL', '').strip()
CONTACT_EMAIL = os.environ.get('CONTACT_EMAIL', '').strip()

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'
