# Generated by Django 6.1 on 2026-09-01 07:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver_name', models.CharField(max_length=50, verbose_name='받는 분')),
                ('phone', models.CharField(max_length=20, verbose_name='연락처')),
                ('address', models.CharField(max_length=255, verbose_name='주소')),
                ('memo', models.CharField(blank=True, max_length=255, verbose_name='배송 메모')),
                ('status', models.CharField(choices=[('PENDING', '결제대기'), ('PAID', '결제완료'), ('SHIPPED', '배송중'), ('DONE', '배송완료'), ('CANCELED', '취소')], default='PENDING', max_length=20, verbose_name='상태')),
                ('total_price', models.PositiveIntegerField(verbose_name='총 결제금액')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='주문일')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='주문자')),
            ],
            options={
                'verbose_name': '주문',
                'verbose_name_plural': '주문',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveIntegerField(verbose_name='구매 당시 가격')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
