# Generated by Django 5.2.17 on 2026-09-28 04:19

import uuid

from django.db import migrations, models


def fill_toss_order_ids(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.filter(toss_order_id=''):
        order.toss_order_id = f'order-{uuid.uuid4().hex}'
        order.save(update_fields=['toss_order_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_id_alter_orderitem_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='결제일시'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_key',
            field=models.CharField(blank=True, max_length=200, verbose_name='PG 결제키'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, verbose_name='결제수단'),
        ),
        migrations.AddField(
            model_name='order',
            name='toss_order_id',
            field=models.CharField(default='', editable=False, max_length=64, verbose_name='PG 주문번호'),
        ),
        migrations.RunPython(fill_toss_order_ids, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='order',
            name='toss_order_id',
            field=models.CharField(default='', editable=False, max_length=64, unique=True, verbose_name='PG 주문번호'),
        ),
    ]
