# Generated by Django 5.2.17 on 2026-09-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_toss_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='address_detail',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='상세 주소'),
        ),
        migrations.AddField(
            model_name='order',
            name='postcode',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='우편번호'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=255, verbose_name='기본 주소'),
        ),
    ]
