# Generated by Django 5.2.17 on 2026-09-28 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_address_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='courier',
            field=models.CharField(blank=True, choices=[('cj', 'CJ대한통운'), ('epost', '우체국택배'), ('hanjin', '한진택배'), ('lotte', '롯데택배'), ('logen', '로젠택배'), ('etc', '기타')], default='', max_length=20, verbose_name='택배사'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='송장번호'),
        ),
    ]
