# Generated by Django 6.1 on 2026-09-01 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='카테고리명')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='슬러그(URL용)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
            ],
            options={
                'verbose_name': '카테고리',
                'verbose_name_plural': '카테고리',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='상품명')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='슬러그(URL용)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='브랜드')),
                ('description', models.TextField(blank=True, verbose_name='상세설명')),
                ('size', models.CharField(blank=True, help_text='예: Free, S, M, 66 등', max_length=50, verbose_name='사이즈')),
                ('condition', models.CharField(choices=[('S', 'S급 (새것 같음)'), ('A', 'A급 (사용감 적음)'), ('B', 'B급 (사용감 있음)'), ('C', 'C급 (사용감 많음, 수선 필요 등)')], default='A', max_length=1, verbose_name='컨디션')),
                ('measurements', models.TextField(blank=True, help_text='예: 어깨 40 / 가슴 50 / 총장 60 (줄바꿈으로 구분)', verbose_name='실측')),
                ('price', models.PositiveIntegerField(verbose_name='가격(원)')),
                ('is_sold', models.BooleanField(default=False, verbose_name='품절 여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='진열 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='products.category', verbose_name='카테고리')),
            ],
            options={
                'verbose_name': '상품',
                'verbose_name_plural': '상품',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='이미지')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='정렬순서')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'verbose_name': '상품 이미지',
                'verbose_name_plural': '상품 이미지',
                'ordering': ['order'],
            },
        ),
    ]
